version: "2.3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "undercast"
      POSTGRES_PASSWORD: "undercast"
      POSTGRES_DB: "undercast"
    ports:
      - "5432:5432"
    restart: always
  app:
    build:
      context: .
      target: prod
    volumes:
      - ./data:/app/data
    environment:
      DB_URL: postgres://undercast:undercast@postgres/undercast
      DATA_DIR: /data
    ports:
      - "8080:8080"
    depends_on:
      - postgres
