version: "2.3"
services:
  app:
    build:
      context: .
      target: prod
    volumes:
      - ./data:/app/data
    environment:
      DB_URL: postgres://undercast:undercast@postgres/undercast
      DATA_DIR: /data
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
    - "27017:27017"
