version: '2'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'undercast'
      POSTGRES_PASSWORD: 'undercast'
      POSTGRES_DB: 'undercast'
    ports:
      - '5432:5432'
    restart: always