version: "2.3"
services:
  app:
    build:
      context: .
      target: prod
    volumes:
      - ./data:/app/data
    environment:
      MONGO_URI: mongodb://mongo
      MONGO_DB_NAME: undercast
      DATA_DIR: /data
    ports:
      - "4242:4242"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
    - "27017:27017"
