version: "2.3"
services:
  app:
    image: dir01/undercast:staging
    volumes:
      - ./data:/app/data
    environment:
      MONGO_URI: mongodb://mongo
      MONGO_DB_NAME: undercast
      DATA_DIR: /data
    env_file:
      - .env
    ports:
      - "9001:4242"
    depends_on:
      - mongo
  mongo:
    image: mongo
