// This file is automatically generated from your CSS. Any edits will be overwritten.
/* eslint-disable @typescript-eslint/interface-name-prefix */
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        notfound: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
