// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	undercast "undercast"

	mock "github.com/stretchr/testify/mock"
)

// Downloader is an autogenerated mock type for the Downloader type
type Downloader struct {
	mock.Mock
}

// Download provides a mock function with given fields: id, source
func (_m *Downloader) Download(id string, source string) error {
	ret := _m.Called(id, source)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, source)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsMatching provides a mock function with given fields: source
func (_m *Downloader) IsMatching(source string) bool {
	ret := _m.Called(source)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(source)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// OnProgress provides a mock function with given fields: _a0
func (_m *Downloader) OnProgress(_a0 func(string, *undercast.DownloadInfo)) {
	_m.Called(_a0)
}
