// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
	"undercast"
)

// Ensure, that DownloaderMock does implement undercast.Downloader.
// If this is not the case, regenerate this file with moq.
var _ undercast.Downloader = &DownloaderMock{}

// DownloaderMock is a mock implementation of undercast.Downloader.
//
//     func TestSomethingThatUsesDownloader(t *testing.T) {
//
//         // make and configure a mocked undercast.Downloader
//         mockedDownloader := &DownloaderMock{
//             DownloadFunc: func(id string, source string) error {
// 	               panic("mock out the Download method")
//             },
//             IsMatchingFunc: func(source string) bool {
// 	               panic("mock out the IsMatching method")
//             },
//             OnInfoFunc: func(onInfo func(id string, info *undercast.DownloadInfo))  {
// 	               panic("mock out the OnInfo method")
//             },
//             OnProgressFunc: func(onProgress func(id string, progress *undercast.DownloadProgress))  {
// 	               panic("mock out the OnProgress method")
//             },
//         }
//
//         // use mockedDownloader in code that requires undercast.Downloader
//         // and then make assertions.
//
//     }
type DownloaderMock struct {
	// DownloadFunc mocks the Download method.
	DownloadFunc func(id string, source string) error

	// IsMatchingFunc mocks the IsMatching method.
	IsMatchingFunc func(source string) bool

	// OnInfoFunc mocks the OnInfo method.
	OnInfoFunc func(onInfo func(id string, info *undercast.DownloadInfo))

	// OnProgressFunc mocks the OnProgress method.
	OnProgressFunc func(onProgress func(id string, progress *undercast.DownloadProgress))

	// calls tracks calls to the methods.
	calls struct {
		// Download holds details about calls to the Download method.
		Download []struct {
			// ID is the id argument value.
			ID string
			// Source is the source argument value.
			Source string
		}
		// IsMatching holds details about calls to the IsMatching method.
		IsMatching []struct {
			// Source is the source argument value.
			Source string
		}
		// OnInfo holds details about calls to the OnInfo method.
		OnInfo []struct {
			// OnInfo is the onInfo argument value.
			OnInfo func(id string, info *undercast.DownloadInfo)
		}
		// OnProgress holds details about calls to the OnProgress method.
		OnProgress []struct {
			// OnProgress is the onProgress argument value.
			OnProgress func(id string, progress *undercast.DownloadProgress)
		}
	}
	lockDownload   sync.RWMutex
	lockIsMatching sync.RWMutex
	lockOnInfo     sync.RWMutex
	lockOnProgress sync.RWMutex
}

// Download calls DownloadFunc.
func (mock *DownloaderMock) Download(id string, source string) error {
	callInfo := struct {
		ID     string
		Source string
	}{
		ID:     id,
		Source: source,
	}
	mock.lockDownload.Lock()
	mock.calls.Download = append(mock.calls.Download, callInfo)
	mock.lockDownload.Unlock()
	if mock.DownloadFunc == nil {
		var (
			out1 error
		)
		return out1
	}
	return mock.DownloadFunc(id, source)
}

// DownloadCalls gets all the calls that were made to Download.
// Check the length with:
//     len(mockedDownloader.DownloadCalls())
func (mock *DownloaderMock) DownloadCalls() []struct {
	ID     string
	Source string
} {
	var calls []struct {
		ID     string
		Source string
	}
	mock.lockDownload.RLock()
	calls = mock.calls.Download
	mock.lockDownload.RUnlock()
	return calls
}

// IsMatching calls IsMatchingFunc.
func (mock *DownloaderMock) IsMatching(source string) bool {
	callInfo := struct {
		Source string
	}{
		Source: source,
	}
	mock.lockIsMatching.Lock()
	mock.calls.IsMatching = append(mock.calls.IsMatching, callInfo)
	mock.lockIsMatching.Unlock()
	if mock.IsMatchingFunc == nil {
		var (
			out1 bool
		)
		return out1
	}
	return mock.IsMatchingFunc(source)
}

// IsMatchingCalls gets all the calls that were made to IsMatching.
// Check the length with:
//     len(mockedDownloader.IsMatchingCalls())
func (mock *DownloaderMock) IsMatchingCalls() []struct {
	Source string
} {
	var calls []struct {
		Source string
	}
	mock.lockIsMatching.RLock()
	calls = mock.calls.IsMatching
	mock.lockIsMatching.RUnlock()
	return calls
}

// OnInfo calls OnInfoFunc.
func (mock *DownloaderMock) OnInfo(onInfo func(id string, info *undercast.DownloadInfo)) {
	callInfo := struct {
		OnInfo func(id string, info *undercast.DownloadInfo)
	}{
		OnInfo: onInfo,
	}
	mock.lockOnInfo.Lock()
	mock.calls.OnInfo = append(mock.calls.OnInfo, callInfo)
	mock.lockOnInfo.Unlock()
	if mock.OnInfoFunc == nil {
		return
	}
	mock.OnInfoFunc(onInfo)
}

// OnInfoCalls gets all the calls that were made to OnInfo.
// Check the length with:
//     len(mockedDownloader.OnInfoCalls())
func (mock *DownloaderMock) OnInfoCalls() []struct {
	OnInfo func(id string, info *undercast.DownloadInfo)
} {
	var calls []struct {
		OnInfo func(id string, info *undercast.DownloadInfo)
	}
	mock.lockOnInfo.RLock()
	calls = mock.calls.OnInfo
	mock.lockOnInfo.RUnlock()
	return calls
}

// OnProgress calls OnProgressFunc.
func (mock *DownloaderMock) OnProgress(onProgress func(id string, progress *undercast.DownloadProgress)) {
	callInfo := struct {
		OnProgress func(id string, progress *undercast.DownloadProgress)
	}{
		OnProgress: onProgress,
	}
	mock.lockOnProgress.Lock()
	mock.calls.OnProgress = append(mock.calls.OnProgress, callInfo)
	mock.lockOnProgress.Unlock()
	if mock.OnProgressFunc == nil {
		return
	}
	mock.OnProgressFunc(onProgress)
}

// OnProgressCalls gets all the calls that were made to OnProgress.
// Check the length with:
//     len(mockedDownloader.OnProgressCalls())
func (mock *DownloaderMock) OnProgressCalls() []struct {
	OnProgress func(id string, progress *undercast.DownloadProgress)
} {
	var calls []struct {
		OnProgress func(id string, progress *undercast.DownloadProgress)
	}
	mock.lockOnProgress.RLock()
	calls = mock.calls.OnProgress
	mock.lockOnProgress.RUnlock()
	return calls
}
